name: BlackShop
version: 1.0.0
api: 3.2.0
main: BlackTeam\BlackShop\EconomyShop
author: BlackTeam
depend: [EconomyAPI]

permissions:
 economyshop.*:
  description: Allows all functions in EconomyShop
  default: op
  children:
   economyshop.shop.*:
    description: Allows all functions about shops
    default: op
    children:
     economyshop.shop.buy:
      description: Allows player to buy from shop
      default: true
     economyshop.shop.create:
      description: Allows player to create shop
      default: op
     economyshop.shop.remove:
      description: Allows player to remove shop
      default: op
